apiVersion: apps/v1
kind: Deployment

metadata:
  name: orderapi
  namespace: microservices
  labels:
    app: orderapi

spec:
  replicas: 2

  selector:
    matchLabels:
      app: orderapi

  template:
    metadata:
      labels:
        app: orderapi

    spec:
      containers:
      - name: orderapi
        image: deepakaksacr.azurecr.io/orderapi:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        env:
        - name: PAYMENT_API_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PAYMENT_API_URL

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
               name: app-secret
               key: DB_PASSWORD

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"