apiVersion: v1
kind: Service

metadata:
  name: orderapi
  namespace: microservices

spec:
  type: ClusterIP

  selector:
    app: orderapi

  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080