apiVersion: v1
kind: Service

metadata:
  name: paymentapi
  namespace: microservices

spec:
  type: ClusterIP

  selector:
    app: paymentapi

  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080