trigger:
  branches:
    include:
      - main
  paths:
    include:
      - AuthApi/**
      - azure-pipelines-auth.yml

pool:
  name: Default

variables:
  buildConfiguration: 'Release'
  imageRepository: 'authapi'
  containerRegistry: 'ACRConnection'
  dockerfilePath: 'AuthApi/Dockerfile'
  tag: '$(Build.BuildId)'

steps:

- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '10.0.x'

- script: |
    dotnet restore AuthApi/AuthApi.csproj
    dotnet build AuthApi/AuthApi.csproj --configuration $(buildConfiguration) --no-restore
  displayName: 'Restore and Build'

- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    command: 'buildAndPush'
    containerRegistry: '$(containerRegistry)'
    repository: '$(imageRepository)'
    dockerfile: '$(dockerfilePath)'
    tags: |
      $(tag)
      latest
- task: KubernetesManifest@1
  displayName: 'Deploy Auth API to AKS'
  inputs:
    action: 'deploy'
    connectionType: 'azureResourceManager'
    azureSubscriptionConnection: 'AKSConnection'
    azureResourceGroup: 'rg-aks-enterprise'
    kubernetesCluster: 'aks-enterprise'
    namespace: 'microservices'
    manifests: |
      k8s/authapi/authapi-deployment.yaml
      k8s/authapi/authapi-service.yaml
    containers: |
      deepakaksacr.azurecr.io/authapi:$(tag)